model:
  meta_architecture: "RBSolver"
  rbsolver:
#    you may need to change this.
#    previous version
#     [
#       [ 8.6602533e-01,  5.0000000e-01,  3.2727594e-09, -3.3480757e-01],
#       [ 2.5000000e-01, -4.3301266e-01, -8.6602539e-01,  7.6554433e-02],
#       [-4.3301272e-01,  7.5000000e-01, -5.0000000e-01,  1.2674038e+00],
#       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.0000000e+00]
#     ]
    init_Tc_c2b: [
      [-1.0000000e+00, -8.7422777e-08,  1.5785288e-24,  2.0000000e-01],
      [ 3.8213709e-15, -4.3711388e-08, -1.0000000e+00,  3.0000001e-01],
      [ 8.7422777e-08, -1.0000000e+00,  4.3711388e-08,  8.9999998e-01],
      [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.0000000e+00]
    ]
    mesh_paths: [
      "assets/xarm_description/meshes/xarm6/visual/base.stl",
      "assets/xarm_description/meshes/xarm6/visual/link1.stl",
      "assets/xarm_description/meshes/xarm6/visual/link2.stl",
      "assets/xarm_description/meshes/xarm6/visual/link3.stl",
      "assets/xarm_description/meshes/xarm6/visual/link4.stl",
      "assets/xarm_description/meshes/xarm6/visual/link5.stl",
      "assets/xarm_description/meshes/xarm6/visual/link6.stl",
      "assets/xarm_gripper/meshes/base_link.STL",
      "assets/xarm_gripper/meshes/left_finger_black.glb",
      "assets/xarm_gripper/meshes/right_finger_black.glb",
    ]
    H: 480 # you may need to change this according to the image size.
    W: 640
datasets:
  train: ("xarm6_real/xarm6_offline/example_right_back",)
  test: "xarm6_real/xarm6_offline/example_right_back"

solver:
  log_interval: 1
  trainer: "rbsolver"
  explore_iters: 10 # the number of iterations for exploration
  num_epochs: 1000 # the number of iterations for optimization
  max_lr: 0.003 # the learning rate for optimization
  batch_size: 100 # a large number to make sure all the images are in one batch
  save_freq: 20
  val_freq: 20
  save_every: True
  save_mode: iteration
dataset:
  xarm_real:
    use_links: [1,2,3,4,5,6,7,9,10,11]
    urdf_path: "assets/xarm6_with_gripper.urdf"
input:
  shuffle: False
dataloader:
  pin_memory: True
test:
  batch_size: 100
