model:
  meta_architecture: "RBSolver"
  rbsolver:
    init_Tc_c2b: [
      [ 9.39692616e-01, -3.42020154e-01, -1.03584945e-08, -2.39069015e-01],
      [-1.71010062e-01, -4.69846278e-01, -8.66025388e-01,  2.56342530e-01],
      [ 2.96198159e-01,  8.13797772e-01, -5.00000000e-01,  7.56001711e-01],
      [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00]
    ]
    mesh_paths: [
      "assets/xarm_description/meshes/xarm6/visual/base.stl",
      "assets/xarm_description/meshes/xarm6/visual/link1.stl",
      "assets/xarm_description/meshes/xarm6/visual/link2.stl",
      "assets/xarm_description/meshes/xarm6/visual/link3.stl",
      "assets/xarm_description/meshes/xarm6/visual/link4.stl",
      "assets/xarm_description/meshes/xarm6/visual/link5.stl",
      "assets/xarm_description/meshes/xarm6/visual/link6.stl",
      "assets/xarm_gripper/meshes/base_link.STL",
      "assets/xarm_gripper/meshes/left_finger_black.glb",
      "assets/xarm_gripper/meshes/right_finger_black.glb",
    ]
    H: 480 # you may need to change this according to the image size.
    W: 640
datasets:
  train: ("xarm6_real/xarm6_offline/20241022_171204/left_back",)
  test: "xarm6_real/xarm6_offline/20241020_164336/left_back"

solver:
  log_interval: 1
  trainer: "rbsolver"
  explore_iters: 10 # the number of iterations for exploration
  num_epochs: 1000 # the number of iterations for optimization
  max_lr: 0.003 # the learning rate for optimization
  batch_size: 100 # a large number to make sure all the images are in one batch
  save_freq: 20
  val_freq: 20
  save_every: True
  save_mode: iteration
dataset:
  xarm_real:
    use_links: [1,2,3,4,5,6,7,9,10,11]
    urdf_path: "assets/xarm6_with_gripper.urdf"
input:
  shuffle: False
dataloader:
  pin_memory: True
test:
  batch_size: 100
